apiVersion: v1
kind: Service
metadata:
  name: python-flask
  labels:
    app: python-flask
spec:
  selector:
    app: python-flask
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      name: http-8080
  type: ClusterIP